### ISSUE TITLE
Regression in 0.16.0 with fill tessellator

### ISSUE THREAD

**Issue by tronical** [nical/lyon#607]
Upgrading to 0.16.0 suddenly caused a failing debug assertion in our code.

I tried making a test for `fill_test.rs` to reproduce it, but somehow I couldn't get the assert to trigger there. However a standalone little main.rs reproduces this:

```rust
use lyon::math::Point;
use lyon::path::PathEvent;
use lyon::tessellation::geometry_builder::VertexBuffers;
use lyon::tessellation::geometry_builder::*;
use lyon::tessellation::{FillOptions, FillTessellator};

fn main() {
    let point = |x, y| Point::new(x, y);

    let path = vec![
        PathEvent::Begin {
            at: point(100., 300.),
        },
        PathEvent::Quadratic {
            from: point(100., 300.),
            ctrl: point(150., 50.),
            to: point(250., 150.),
        },
        PathEvent::Cubic {
            from: point(250., 150.),
            ctrl1: point(250., 300.),
            ctrl2: point(300., 300.),
            to: point(300., 450.),
        },
        PathEvent::Line {
            from: point(300., 450.),
            to: point(300., 450.),
        },
        PathEvent::Quadratic {
            from: point(300., 450.),
            ctrl: point(299.9, 481.),
            to: point(321., 503.),
        },
        PathEvent::Quadratic {
            from: point(321., 503.),
            ctrl: point(343.9, 525.),
            to: point(375., 525.),
        },
        PathEvent::Quadratic {
            from: point(375., 525.),
            ctrl: point(406., 524.),
            to: point(428., 503.),
        },
        PathEvent::Quadratic {
            from: point(428., 503.),
            ctrl: point(450., 581.),
            to: point(450., 450.),
        },
        PathEvent::Line {
            from: point(450., 450.),
            to: point(550., 300.),
        },
        PathEvent::End {
            first: point(100., 300.),
            last: point(550., 300.),
            close: true,
        },
    ];

    let mut buffers: VertexBuffers<Point, u16> = VertexBuffers::new();

    let fill_opts = FillOptions::default();
    let mut fill_tesselator = FillTessellator::new();
    fill_tesselator
        .tessellate(path, &fill_opts, &mut simple_builder(&mut buffers))
        .unwrap();
}
```

Running this against 0.15.9 works quietly, while 0.16.0 fails at run-time with a failing assertion:

```shell
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', /Users/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.16.0/src/fill.rs:813:9
...
  12: std::panicking::begin_panic_fmt
             at src/libcore/alloc/layout.rs:364
  13: lyon_tessellation::fill::FillTessellator::check_active_edges
             at /Users/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.16.0/src/fill.rs:813
  14: lyon_tessellation::fill::FillTessellator::tessellator_loop
             at /Users/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.16.0/src/fill.rs:661
  15: lyon_tessellation::fill::FillTessellator::tessellate_impl
             at /Users/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.16.0/src/fill.rs:596
  16: lyon_tessellation::fill::FillTessellator::tessellate
             at /Users/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.16.0/src/fill.rs:505
  17: lyontest::main
             at src/main.rs:64
  18: std::rt::lang_start::{{closure}}
             at /Users/simon/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  21: std::panicking::try
             at src/libstd/panicking.rs:325
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: std::rt::lang_start
             at /Users/simon/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
  25: main
```

**Comment by nical** [comment]
Thanks for filing this and providing a test case. It appears that I fixed this in #583 which I must have fogotten to uplift to the 0.16 branch. I'll publish the fix soon.

**Comment by nical** [comment]
Fix in published in [version 0.16.1](https://crates.io/crates/lyon_tessellation/0.16.1).

**Comment by tronical** [comment]
I can still reproduce the same assertion with `lyon = { version = "0.16.1" }` in `Cargo.toml` . However using the master branch (`lyon = { git = "https://github.com/nical/lyon", branch = "master" }` in `Cargo.toml`) works.

It seems that the changes in #583 affected for example `geom/src/flatten_cubic.rs` and `path/src/builder.rs` and the corresponding `lyon_geom` and `lyon_path` crates are still on 0.16.0 on crates.io.

**Comment by nical** [comment]
Ah, yes indeed, thanks. Hopefully I got it right in [Version 0.16.2](https://crates.io/crates/lyon_tessellation/0.16.2).

**Comment by tronical** [comment]
Yep, works now. Thanks!
